### ISSUE TITLE
Error codes reported by the ROS driver

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xarm_ros#107]
The xarm manual details a number of error codes, all with letter prefixes; whereas the ROS driver reports a numeric error code only. Is there a guideline for interpreting the ROS driver numeric error codes? are they always going to align with the controller error codes (Cxx page 85 of the dev manual)?

**Comment by penglongxiang** [comment]
Hi @BryanStuurman, Normally the error codes you get from "`get_err`" service or the "`err`" filed in "`xarm_states`" message are consistent with **controller error code** (Cxx codes popped up in xArm Studio). We have noticed the inconvenient situation and will try to add more interpretation to the numerical codes in next updates.

**Comment by BryanStuurman** [comment]
Thanks for the information.

A question: "Normally" they coincide with Cxx error codes. under what conditions do they **not** coincide with Cxx error codes?

**Comment by penglongxiang** [comment]
Since the error is reported by controller, if the communication channel has no problem, it should always coincide with Cxx code. I have not observed inconsistency on my side yet. If you have experienced the abnormal situation please report to us and we will investigate immediately, thank you.

BTW, we have already added Cxx code interpretation in the latest commit, please update if you need this function.
