### ISSUE TITLE
xArm6 Jumps when robot is intiailized using the drivers and moveit package

### ISSUE THREAD

**Issue by nitish3693** [xArm-Developer/xarm_ros#147]
Getting the following error and warning

![image](https://user-images.githubusercontent.com/75649112/201676343-777006e5-3aa6-4873-901d-9be18bde602f.png)

**Comment by penglongxiang** [comment]
If network time sync is a requirement, maybe you can refer to [this article](https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04) and setup the sync with `ntpd`, which is said to adjust system time gradually instead of abruptly. Please note we have not tested or verified this configuration. Just information sharing.

**Comment by nitish3693** [comment]
Used the instruction in the [article](https://dev.to/fmtweisszwerg/how-to-disable-systemd-timesyncd-ntp-service-via-systemd-5fkd)  to disable the network time sync. 

After boot

**Comment by penglongxiang** [comment]
Hi Nitish, did this configuration solve the jump issue?

**Comment by nitish3693** [comment]
Hi @penglongxiang, we have not seen the jump since disabling the network time sync.

**Comment by penglongxiang** [comment]
Great! Thanks for the feedback.
