### ISSUE TITLE
Question about collision meshes

### ISSUE THREAD

**Issue by JuliusSustarevas** [xArm-Developer/xarm_ros#75]
Hi,
I have a question about the use of meshes for collisions in the robot description. 
The standard practice usually says that collisions should be done using generic shapes or highly simplified meshes. But here the same visual meshes are used in <collision> tags for arm links.  Do you not find that this ruins performance?  Just want to understand the decision making. Thanks

**Comment by penglongxiang** [comment]
Hi @JuliusSustarevas , Indeed we did not use simplified mesh models for collision checking, since heavy influence on the performance is not reported so far, I guess collision matrix setting in moveit_configuration helped eliminating unnecessary calculations. We may add simplified models in the future. Thanks for noticing.
